In [29]:
import pandas as pd

In [30]:
bookings = pd.read_csv('/projects/mini_projects/dataset/bookings.csv', sep =";")

 - ### Check the size of the table, variable types, and then display the first 7 rows to examine the data.

In [31]:
# check the size of the table
bookings.shape

(119390, 21)

In [32]:
# check the variable types
bookings.dtypes

Hotel                         object
Is Canceled                    int64
Lead Time                      int64
arrival full date             object
Arrival Date Year              int64
Arrival Date Month            object
Arrival Date Week Number       int64
Arrival Date Day of Month      int64
Stays in Weekend nights        int64
Stays in week nights           int64
stays total nights             int64
Adults                         int64
Children                     float64
Babies                         int64
Meal                          object
Country                       object
Reserved Room Type            object
Assigned room type            object
customer type                 object
Reservation Status            object
Reservation status_date       object
dtype: object

In [33]:
# display the first 7 rows of the table
bookings.head(7)

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-03

 - ### Let's convert the column names to lowercase and replace spaces with underscores.

In [34]:
# show all column names
list(bookings)

['Hotel',
 'Is Canceled',
 'Lead Time',
 'arrival full date',
 'Arrival Date Year',
 'Arrival Date Month',
 'Arrival Date Week Number',
 'Arrival Date Day of Month',
 'Stays in Weekend nights',
 'Stays in week nights',
 'stays total nights',
 'Adults',
 'Children',
 'Babies',
 'Meal',
 'Country',
 'Reserved Room Type',
 'Assigned room type',
 'customer type',
 'Reservation Status',
 'Reservation status_date']

In [35]:
bookings.columns = bookings.columns.str.lower().str.replace(' ','_')

In [36]:
# check that all names have changed correctly
bookings.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_full_date',
       'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'stays_total_nights', 'adults', 'children',
       'babies', 'meal', 'country', 'reserved_room_type', 'assigned_room_type',
       'customer_type', 'reservation_status', 'reservation_status_date'],
      dtype='object')

 - ### Specify the top 5 countries from which users made the highest number of successful bookings.

In [37]:
bookings.groupby('country').stays_total_nights.sum().sort_values(ascending=False)
# PRT    141654
# GBR     58092
# FRA     36547
# ESP     26358
# DEU     25787

country
PRT    141654
GBR     58092
FRA     36547
ESP     26358
DEU     25787
        ...
DJI         1
MLI         1
ASM         1
HND         1
BFA         1
Name: stays_total_nights, Length: 177, dtype: int64

 - ### What is the average number of nights hotels of different types are booked for?

In [38]:
bookings.groupby(['hotel'], as_index=False).agg({'stays_total_nights': 'mean'}).sort_values('stays_total_nights', ascending=False)

          hotel  stays_total_nights
1  Resort Hotel            4.318547
0    City Hotel            2.978142

 -  ### Which countries had the highest number of successful bookings? A booking is considered successful if it was not later canceled (variable is_canceled). Choose the top 5 countries as the answer

In [39]:
bookings.loc[bookings.is_canceled == 0].country.value_counts().head(5)

PRT    21071
GBR     9676
FRA     8481
ESP     6391
DEU     6069
Name: country, dtype: int64

 - ### How many observations in the dataset have a discrepancy between the assigned room type (assigned_room_type) and the originally reserved room type (reserved_room_type), which can occur due to reasons such as overbooking?

In [40]:
bookings.query('reserved_room_type != assigned_room_type').shape[0]

14917

 - ### Now, let's analyze the planned arrival dates (arrival_date_year). Which month had the most bookings in 2016? Did the most popular month change in 2017?

In [41]:
bookings.query('arrival_date_year == 2016').value_counts('arrival_date_month')

arrival_date_month
October      6203
May          5478
April        5428
September    5394
June         5292
August       5063
March        4824
July         4572
November     4454
February     3891
December     3860
January      2248
dtype: int64

In [42]:
bookings.query('arrival_date_year == 2017').value_counts('arrival_date_month')

arrival_date_month
May         6313
April       5661
June        5647
July        5313
March       4970
August      4925
February    4177
January     3681
dtype: int64

- ### Let's group the data by years and then check in which month (arrival_date_month) bookings for City Hotel were canceled most frequently in 2015, 2016, and 2017.

In [43]:
(
    bookings
        .query('hotel == City Hotel' and 'is_canceled == 1')
        .groupby('arrival_date_year')
        .arrival_date_month
        .value_counts()
)

arrival_date_year  arrival_date_month
2015               September             2094
                   October               1732
                   August                1598
                   July                  1259
                   December               973
                   November               486
2016               October               2514
                   June                  2096
                   April                 2061
                   September             2022
                   May                   1915
                   August                1825
                   November              1636
                   July                  1499
                   March                 1477
                   December              1398
                   February              1337
                   January                557
2017               May                   2762
                   April                 2463
                   June                  2439
                   July                  1984
                   August                1816
                   March                 1672
                   February              1359
                   January               1250
Name: arrival_date_month, dtype: int64

 - ### Let's examine the numerical characteristics of three columns: (adults), (children), and (babies). Determine which of them has the highest mean value.

In [44]:
bookings[['adults', 'children', 'babies']].mean()

adults      1.856403
children    0.103890
babies      0.007949
dtype: float64

 - ### Let's create a column named 'total_kids' by combining the 'children' and 'babies' columns. For which type of hotels did the variable's mean value turn out to be the highest?

In [45]:
bookings['total_kids'] = bookings.children + bookings.babies

In [46]:
bookings.head(1)

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date,total_kids
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01,0.0

In [47]:
bookings.groupby('hotel').total_kids.mean().round(2)

hotel
City Hotel      0.10
Resort Hotel    0.14
Name: total_kids, dtype: float64

 - ### Not all bookings were successful (is_canceled), so we can calculate how many customers were lost in the process. In other words, we can calculate a metric called Churn Rate.

 - ##### Churn rate is the percentage of subscribers (e.g., for push notifications from a website) who unsubscribed from the communication channel, discontinued the service within a certain period. In our case, the Churn Rate is the percentage of customers who canceled their booking. For example, let's see how this metric is related to the presence of children among customers!

 - ##### We'll create a variable 'has_kids' that takes the value True if the customer indicated at least one child during booking (total_kids), otherwise False. Then, we'll check among which group of users the churn rate is higher."

In [48]:
bookings['total_kids'] > 0

0         False
1         False
2         False
3         False
4         False
          ...
119385    False
119386    False
119387    False
119388    False
119389    False
Name: total_kids, Length: 119390, dtype: bool

In [49]:
bookings['has_kids'] = bookings['total_kids'] > 0

In [50]:
bookings.head()

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date,total_kids,has_kids
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01,0.0,False
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01,0.0,False
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02,0.0,False
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02,0.0,False
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03,0.0,False

In [51]:
no_kids_churn = bookings.query('is_canceled == 1 and has_kids == False').shape[0] / bookings.query('has_kids == False').shape[0]
no_kids_churn = round(no_kids_churn * 100, 2)

In [52]:
no_kids_churn

37.22

In [53]:
has_kids_churn = bookings.query('is_canceled == 1 and has_kids == True').shape[0] / bookings.query('has_kids == True').shape[0]
has_kids_churn = round(has_kids_churn * 100, 2)

In [54]:
has_kids_churn

34.92

#### Conclusion: Churn rate is higher among customers without children than among customers with children.